### ISSUE TITLE
java.lang.RuntimeException: setParameters failed

### ISSUE THREAD

**Issue by AizazAZ** [Yalantis/CameraModule#4]
Nexus 7 (2012) Model
Android 4.4.4
Build KTU84P
Tuesday March 18 2014

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.beusoft.liuying/com.yalantis.cameramodule.activity.CameraActivity}: java.lang.RuntimeException: setParameters failed
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2184)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
            at android.app.ActivityThread.access$800(ActivityThread.java:135)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5001)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.RuntimeException: setParameters failed
            at android.hardware.Camera.native_setParameters(Native Method)
            at android.hardware.Camera.setParameters(Camera.java:1651)
            at com.yalantis.cameramodule.fragment.CameraFragment.initParams(CameraFragment.java:458)
            at com.yalantis.cameramodule.fragment.CameraFragment.init(CameraFragment.java:176)
            at com.yalantis.cameramodule.fragment.CameraFragment.onCreate(CameraFragment.java:132)
            at android.app.Fragment.performCreate(Fragment.java:1678)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:859)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)
            at android.app.BackStackRecord.run(BackStackRecord.java:684)
            at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1447)
            at android.app.Activity.performStart(Activity.java:5240)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2157)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
            at android.app.ActivityThread.access$800(ActivityThread.java:135)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5001)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by AizazAZ** [comment]
Parameter information 

result = {Camera$Parameters@830044455512} 
 mMap = {LinkedHashMap@830044334704}  size = 61
  0 = {LinkedHashMap$LinkedEntry@830034890536} "video-size" -> "1920x1080"
  1 = {LinkedHashMap$LinkedEntry@830034886848} "preferred-preview-size-for-video" -> "1920x1080"
  2 = {LinkedHashMap$LinkedEntry@830034880592} "preview-size-values" -> "1920x1080,1280x768,1280x720,1024x768,800x600,800x480,720x480,640x480,352x288,320x240,176x144"
  3 = {LinkedHashMap$LinkedEntry@830034879184} "video-size-values" -> "1920x1080,1280x768,1280x720,1024x768,800x600,800x480,720x480,640x480,352x288,320x240,176x144"
  4 = {LinkedHashMap$LinkedEntry@830034876600} "preview-format" -> "yuv420sp"
  5 = {LinkedHashMap$LinkedEntry@830034875072} "preview-format-values" -> "yuv420p,yuv420sp,"
  6 = {LinkedHashMap$LinkedEntry@830034854648} "preview-frame-rate" -> "15"
  7 = {LinkedHashMap$LinkedEntry@830034852472} "preview-fps-range" -> "15000,15000"
  8 = {LinkedHashMap$LinkedEntry@830034852296} "preview-fps-range-values" -> "(15000,15000),(24000,24000),(15000,30000),(30000,30000)"
  9 = {LinkedHashMap$LinkedEntry@830034852056} "preview-frame-rate-values" -> "15,24,30"
  10 = {LinkedHashMap$LinkedEntry@830034815920} "picture-size-values" -> "2592x1944,2048x1536,1920x1080,1600x1200,1280x768,1280x720,1024x768,800x600,800x480,720x480,640x480,352x288,320x240,176x144"
  11 = {LinkedHashMap$LinkedEntry@830034813608} "picture-format" -> "jpeg"
  12 = {LinkedHashMap$LinkedEntry@830034805392} "picture-format-values" -> "jpeg"
  13 = {LinkedHashMap$LinkedEntry@830034786528} "jpeg-thumbnail-width" -> "320"
  14 = {LinkedHashMap$LinkedEntry@830034785648} "jpeg-thumbnail-height" -> "240"
  15 = {LinkedHashMap$LinkedEntry@830043050280} "jpeg-thumbnail-size-values" -> "512x288,480x288,256x154,432x288,320x240,176x144,0x0"
  16 = {LinkedHashMap$LinkedEntry@830043003320} "jpeg-thumbnail-quality" -> "90"
  17 = {LinkedHashMap$LinkedEntry@830042994072} "jpeg-quality" -> "90"
  18 = {LinkedHashMap$LinkedEntry@830035617280} "rotation" -> "0"
  19 = {LinkedHashMap$LinkedEntry@830035605944} "whitebalance" -> "auto"
  20 = {LinkedHashMap$LinkedEntry@830035578128} "whitebalance-values" -> "auto,incandescent,fluorescent,warm-fluorescent,daylight,cloudy-daylight,twilight,shade"
  21 = {LinkedHashMap$LinkedEntry@830035539816} "effect" -> "none"
  22 = {LinkedHashMap$LinkedEntry@830035539312} "effect-values" -> "none,mono,negative,solarize,sepia,posterize,whiteboard,blackboard,aqua"
  23 = {LinkedHashMap$LinkedEntry@830035400288} "antibanding" -> "auto"
  24 = {LinkedHashMap$LinkedEntry@830035297264} "antibanding-values" -> "off,60hz,50hz,auto"
  25 = {LinkedHashMap$LinkedEntry@830035190760} "scene-mode" -> "auto"
  26 = {LinkedHashMap$LinkedEntry@830034998688} "scene-mode-values" -> "auto,landscape,snow,beach,sunset,night,portrait,sports,steadyphoto,candlelight,fireworks,party,night-portrait,theatre,action"
  27 = {LinkedHashMap$LinkedEntry@830034922424} "flash-mode-values" -> "off"
  28 = {LinkedHashMap$LinkedEntry@830034903800} "focus-mode" -> "auto"
  29 = {LinkedHashMap$LinkedEntry@830034871488} "focus-mode-values" -> "infinity,auto,macro,continuous-video,continuous-picture"
  30 = {LinkedHashMap$LinkedEntry@830034846312} "max-num-focus-areas" -> "1"
  31 = {LinkedHashMap$LinkedEntry@830044195304} "focus-areas" -> "(0,0,0,0,0)"
  32 = {LinkedHashMap$LinkedEntry@830044109336} "focal-length" -> "2.95"
  33 = {LinkedHashMap$LinkedEntry@830043667704} "horizontal-view-angle" -> "63.8164"
  34 = {LinkedHashMap$LinkedEntry@830043576680} "vertical-view-angle" -> "49.7954"
  35 = {LinkedHashMap$LinkedEntry@830043354192} "exposure-compensation" -> "0"
  36 = {LinkedHashMap$LinkedEntry@830043110368} "max-exposure-compensation" -> "12"
  37 = {LinkedHashMap$LinkedEntry@830043019240} "min-exposure-compensation" -> "-12"
  38 = {LinkedHashMap$LinkedEntry@830035588936} "exposure-compensation-step" -> "0.166667"
  39 = {LinkedHashMap$LinkedEntry@830035353592} "auto-exposure-lock" -> "false"
  40 = {LinkedHashMap$LinkedEntry@830035165216} "auto-exposure-lock-supported" -> "true"
  41 = {LinkedHashMap$LinkedEntry@830034965000} "auto-whitebalance-lock" -> "false"
  42 = {LinkedHashMap$LinkedEntry@830034915536} "auto-whitebalance-lock-supported" -> "true"
  43 = {LinkedHashMap$LinkedEntry@830034882288} "max-num-metering-areas" -> "1"
  44 = {LinkedHashMap$LinkedEntry@830034858816} "metering-areas" -> "(0,0,0,0,0)"
  45 = {LinkedHashMap$LinkedEntry@830034835624} "zoom" -> "0"
  46 = {LinkedHashMap$LinkedEntry@830034816200} "max-zoom" -> "99"
  47 = {LinkedHashMap$LinkedEntry@830034789896} "zoom-ratios" -> "100,103,106,109,112,115,118,121,124,127,130,133,136,139,142,145,148,151,154,157,160,163,166,169,172,175,178,181,184,187,190,193,196,199,203,206,209,212,215,218,221,224,227,230,233,236,239,242,245,248,251,254,257,260,263,266,269,272,275,278,281,284,287,290,293,296,299,303,306,309,312,315,318,321,324,327,330,333,336,339,342,345,348,351,354,357,360,363,366,369,372,375,378,381,384,387,390,393,396,399"
  48 = {LinkedHashMap$LinkedEntry@830034749568} "zoom-supported" -> "true"
  49 = {LinkedHashMap$LinkedEntry@830044265720} "smooth-zoom-supported" -> "false"
  50 = {LinkedHashMap$LinkedEntry@830044238600} "focus-distances" -> "Infinity,Infinity,Infinity"
  51 = {LinkedHashMap$LinkedEntry@830044026560} "max-num-detected-faces-hw" -> "0"
  52 = {LinkedHashMap$LinkedEntry@830043637760} "max-num-detected-faces-sw" -> "0"
  53 = {LinkedHashMap$LinkedEntry@830043635832} "video-frame-format" -> "android-opaque"
  54 = {LinkedHashMap$LinkedEntry@830043616976} "recording-hint" -> "false"
  55 = {LinkedHashMap$LinkedEntry@830043587712} "video-snapshot-supported" -> "true"
  56 = {LinkedHashMap$LinkedEntry@830043421808} "video-stabilization" -> "false"
  57 = {LinkedHashMap$LinkedEntry@830043150088} "video-stabilization-supported" -> "false"
  58 = {LinkedHashMap$LinkedEntry@830044716264} "flash-mode" -> "on"
  59 = {LinkedHashMap$LinkedEntry@830035589912} "preview-size" -> "1024x768"
  60 = {LinkedHashMap$LinkedEntry@830044025984} "picture-size" -> "2592x1944"

**Comment by AizazAZ** [comment]
Fixed and created a pull request.
